blog/apps/noticias/urls.py
from django.urls import path

from . import views

# LA URL EMPIEZA CON Noticias/ <este archivo>
	
app_name = 'noticias'
	
urlpatterns = [
    
    path('', views.ultimasNoti, name = 'ultima'),
    # path('', views.Mostrar.as_view(), name = 'noticias'),
    path('Detalles/<int:pk>', views.detalle_noticia, name = 'detalle'),
    path('Categoria/<int:pk>', views.filtro_categoria, name = 'filtro'),
    path('Acendente/', views.filtro_asce, name = 'asce'),
    path('', views.filtro_desc, name = 'desc'),
	
 
    path('Comentario/',views.Comentario_add, name= 'comentar'),

]

blog/apps/usuarios/urls.py
from django.urls import path

from . import views

# LA URL EMPIEZA CON Noticias/ <este archivo>
	
app_name = 'usuarios'
	
urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),
	
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    
    path('',views.Home, name = 'home'),
    path('Historia/',views.Historia, name= 'historia'),
    path("noticias/",include('apps.noticias.urls')),
    # path("noticias/",views.Noticias,name='noticias'),
    path('Usuario/',include('apps.usuarios.urls')),
    
    
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"), 
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/noticias/models.py
from django.db import models
from django.conf import settings

class Categoria(models.Model):
    
    nombre = models.CharField(max_length = 60)
    
    def __str__(self):
        return self.nombre

class Noticia(models.Model):
    
    titulo = models.CharField(max_length = 150)
    cuerpo = models.TextField()
    resumen = models.TextField(null=True)
    imagen = models.ImageField(upload_to = 'noticias')
    categoría_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    fecha = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.titulo

class Comentario(models.Model):
    
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
    comentario = models.TextField(max_length=200, blank=True,null=True)
    fecha = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.comentario 

blog/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usuario(AbstractUser):
    pass

blog/apps/usuarios/forms.py
from django import forms


from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]
    
    

blog/apps/noticias/views.py
from datetime import timezone
from django.shortcuts import render,redirect
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Noticia, Categoria, Comentario
from django.urls import reverse_lazy

from apps.usuarios.models import Usuario


def ultimasNoti(request):
    noticiaUlt = Noticia.objects.order_by('id').reverse()[:3]
    noticia = Noticia.objects.all()
    categoria = Categoria.objects.all().order_by('nombre')
    # Modifcicar para agrear antiguo y nuevo

    
        
    context ={'noticiaUlt':noticiaUlt,
              'noticia':noticia,
              'categoria':categoria,
              
              }
    return render(request,'noticia/noticias.html',context)


def detalle_noticia(request, pk):
    n = Noticia.objects.get(pk = pk)
    c = Comentario.objects.all().filter(noticia = n.pk).order_by('-id')
    context= {'noticia':n,
              'comentario':c}
    return render(request,'noticia/detalle.html',context)



def filtro_categoria(request,pk):
    n = Noticia.objects.filter( categoría_noticia = pk)
    print(n.__len__)
    ban = False
    cont = 0
    for i in n:
        cont +=1
    if cont == 0:
        ban = False
    else:
        ban = True
    noticiaUlt = Noticia.objects.order_by('id').reverse()[:3]
    noticia = Noticia.objects.all()
    categoria = Categoria.objects.all()
    context= {'filtro':n,
              'noticiaUlt':noticiaUlt,
              'noticia':noticia,
              'categoria':categoria,
              'ban':ban}
    return render(request,'noticia/categoria.html',context)


def filtro_desc(request):
    noticiaUlt = Noticia.objects.order_by('id').reverse()[:3]
    noticia = Noticia.objects.all()
    categoria = Categoria.objects.all()
    nuevas = Noticia.objects.all().order_by('id')
    context= {
              'noticiaUlt':noticiaUlt,
              'noticia':noticia,
              'categoria':categoria,
              'nuevas':nuevas}
    return render(request,'noticia/desc.html',context)

def filtro_asce(request):
    noticiaUlt = Noticia.objects.order_by('id').reverse()[:3]
    noticia = Noticia.objects.all()
    categoria = Categoria.objects.all()
    antiguo = Noticia.objects.all().order_by('id').reverse()
    
    context= {
              'noticiaUlt':noticiaUlt,
              'noticia':noticia,
              'categoria':categoria,
              'antiguo':antiguo}
    return render(request,'noticia/asce.html',context)

@login_required
def Comentario_add(request):
    com = request.POST.get('comentario',None)
    usu = request.user
    noti = request.POST.get('id_noticia', None)# OBTENGO LA PK
    noticia = Noticia.objects.get(pk = noti) #BUSCO LA NOTICIA CON ESA PK
    coment = Comentario.objects.create(usuario = usu, noticia = noticia, comentario = com)

    return redirect(reverse_lazy('noticias:detalle', kwargs={'pk':noti}))
    

blog/apps/usuarios/views.py
# Create your views here.
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegistroForm

class Registro(CreateView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('login')
	template_name = 'usuarios/registro.html'

blog/blog/views.py
from django.shortcuts import render

def Base(request):
    return render(request,'base.html')

def Home(request):
    return render(request,'home.html')

def Noticias(request):
    return render(request, 'noticias.html')

def Historia(request):
    return render(request, 'historia.html')

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/historia.css' %}">
    <link rel="stylesheet" href="{% static 'css/header/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/header/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/main/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/main/ubicacion.css' %}">
    <link rel="stylesheet" href="{% static 'css/main/contacto.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/noticias/main/main_noticias.css' %}">
    <link rel="stylesheet" href="{% static 'css/noticias/main/article.css' %}">
    <link rel="stylesheet" href="{% static 'css/noticias/main/detalle.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <title>Asociacion Juntos en accion |{% block title %}{% endblock %}</title>
</head>
<body id="inicio">
    <nav  class="nav">
        <div class="logo">
            <h1>ASOCIACIÓN CIVIL</h1>
            <p>Juntos en Acción</p>
        </div>
        <div class="contenedor_nav">
            <div class="navigation">
                <ul>
                    <li class="home">
                        <a  href="{% url 'home'%}">Inicio</a>
                    </li>
                    <li class="mision">
                        <a  href="#mision">Misión</a>
                    </li>
                    <li class="historia">
                        <a  href="{% url 'historia' %}">Historia</a>
                    </li>
                    <li class="contacto">
                        <a  href="#footer">Contactos</a>
                    </li>
                    <li class="noticias">
                        <a  href="{% url 'noticias:ultima' %}">Noticias</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="admin">
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="login">
                {% comment %} user.is_authenticated  {% endcomment %}
                {% if user.is_authenticated %}
                <span class="span_login"><a href="{% url 'logout' %}">Cerrar Sesión</a></span>
                <p class="bienvenido">Hola {{user.username | title}}, nos gusta verte de nuevo</p>
                {% else %}
                <span class="span_login"><a href="{% url 'login' %}">Ingresar</a></span>
                <span class="span_login"><a href="{% url 'usuarios:registro' %}">Registrarse</a></span>
                {% endif %}
            </div>
        </div>
        <span class="menu">
            <img src="{% static 'img/menu.png' %}" alt="">
        </span>
    </nav>
    {% block contenedor %}
    {% endblock  %}
    <section class="main_telf">
        <div class="card_telf correo">
            <img src="{% static 'img/iconoCorreo.png' %}" alt="Icono Correo" class="main_iconos">
            <h3 class="telf_titulo">Envíanos un correo al:</h3>
            <ul ul class="ul_telf">
                <li><a href="mailto:uep143.sp.chaco@gmail.com" subject="subject text">uep143.sp.chaco@gmail.com (correo de la UEP)</a></li>
                <li><a href="mailto:sandraccpa@hotmail.com" subject="subject text">sandraccpa@hotmail.com (correo de la presidente)</a></li>
            </ul>
        </div>
        <div class="card_telf telefono">
            <img src="{% static 'img\iconoContactos.png' %}" alt="Icono Contactos" class="main_iconos">
            <h3 class="telf_titulo">Nuestros teléfonos:</h3>
            <ul ul class="ul_telf">
                <li><a href="tel:+5493644733177" title="Teléfono UEP">3644733177 (N° de la UEP)</a></li>
                <li><a href="tel:+5493644673583" title="Teléfono Presidente">3644673583 (N° de la presidente)</a></li>
            </ul>
        </div>
        <div class="card_telf redes">
            <img src="{% static 'img\iconoRedes.png'%}" alt="Icono Redes" class="main_iconos">
            <h3 class="telf_titulo">Nuestras redes:</h3>
            <ul ul class="ul_telf">
                <li><a href="https://www.facebook.com/profile.php?id=100064567493574" target="_blank" title="Facebook">Facebook: Asociacion Civil Juntos En Accion</a></li>
            </ul>
        </div>
        <div class="card_telf scan">
            <img src=" {% static 'img\Escanear.png' %}" alt="Scann" class="main_scann">
        </div>
    </section>
    <footer id="footer">
        <p class="info2">Creado por</p>
        <img src="{% static 'img\logoGrupal2.png' %}" alt="Logo Grupal">
    </footer>
    <div class="up">
        <a href="#inicio">^</a>
    </div>
    <script src="{% static 'js/main.js'%}"></script>
    <script src="{% static 'js/validaciones.js'%}"></script>
    <script src="{% static 'js/ultimasNoticias.js'%}"></script>
</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}  
{% block title %} Home{% endblock %} 
    {% block contenedor %}
    <header class="info">
        <div class="contenedorInfo">
            <div class="header_text">
                <h2>¿QUIÉNES SOMOS?</h2> 
                <p> 
                    JUNTOS EN ACCION  es una Asociación Civil sin fines de lucro formada por ciudadanos al servicio de las personas con discapacidad. Nuestros principales objetivos son: a) Apoyar, contener y asesorar, propiciando el involucramiento de las familias y la sensibilización de la comunidad. b) Crear espacios priorizando actividades dentro de la recreación y capacitación laboral. c) Resaltar la  importancia de la inclusión social y laboral de las personas con discapacidad, para su realización personal. d) Insertar al joven con discapacidad en el mundo laboral. La institución está dirigida y administrada por una Comisión Directiva compuesta de un presidente, un secretario, un tesorero, un vocal titular y un vocal suplente y también una comisión Revisora de Cuentas compuesta por un miembro Titular y uno Suplente.
                </p>
                </div>
            <div class="header_imagenes">
                <div class="img1">
                    <img src="{% static 'img/logoPrincipal.png'%}" alt="Logo-Principal" class="imagen1">
                </div>
                <div class="img2">
                    <img src="{% static 'img/logoEscuela.png'%}" alt="Logo-Escuela" class="imagen2">
                </div>
            </div>
        </div>
    </header>
    <main id="mision">
        <section class="main_info">
            <div class="main_card_contenedor">
                <div  class="card_info">
                    <h2>Misión-Visión</h2>
                    <p class="mision2">Para quienes formamos parte de “JUNTOS EN ACCION” las personas con discapacidad son titulares de los mismos derechos fundamentales que el resto de los ciudadanos. El 1° artículo de la Declaración Universal de los Derechos Humanos (la cual Argentina ha ratificado e incluido en nuestra Constitución Nacional) declara: “Todos los seres humanos son libres e iguales en dignidad y derechos.” A fin de alcanzar esa meta, todas las comunidades deben celebrar la diversidad en el seno de sí mismas, y deben asegurar que las personas con discapacidad puedan disfrutar de las distintas clases de derechos humanos: civiles, políticos, sociales, económicos y culturales reconocidos por las distintas Convenciones Internacionales y la Constitución Nacional y Provincial. Creemos en una concepción donde las personas con discapacidad poseen facultad para decidir sobre sus propias vidas, mientras su discapacidad no impida esto, en oposición a una concepción “paternalista” como la que ha regido en las sociedades del mundo hasta no hace mucho y que, en algunas, tal vez la nuestra también, todavía se encuentra vigente. Los viejos enfoques basados en gran medida en la compasión y en la indefensión para nosotros son inaceptables tratándose de personas que no se ven impedidas de insertarse en la sociedad. Las personas con discapacidad reclaman la igualdad de oportunidades y de acceso a los recursos sociales, como, por ejemplo, el trabajo, una educación integradora, el acceso a las nuevas tecnologías, los servicios sociales y sanitarios, el deporte y actividades de ocio, a productos, bienes y servicios de consumo.</p>
                </div>
            </div>
            <div class="main_card_contenedor">
                <div class="card_info objetivo">
                    <h2>PLAN DE ACCIÓN</h2>
                        <ul>
                            <li>Una alianza fuerte entre el Gobierno y las organizaciones con discapacidad es el requisito básico para progresar de la forma más eficaz hacia la igualdad de oportunidades y la participación social de las personas con discapacidad. </li>
                            <li>Buscamos el diálogo y la cooperación con las organizaciones que trabajan por la discapacidad.</li>
                            <li>Las organizaciones de discapacidad, como representantes de las personas con discapacidad, tienen una importante responsabilidad de garantizar el éxito de estos fines. Para ello deben dirigirse activamente a todos los actores sociales más relevantes, proponiendo medidas concretas y tratando de establecer articulación y cooperación a largo plazo.</li>
                            <li>Las empresas privadas deben aumentar sus esfuerzos para incluir, mantener y promocionar espacios para las personas con discapacidad en su plantilla y diseñar sus productos y servicios para que sean accesibles a las personas con discapacidad. Los empresarios deben revisar sus políticas internas para asegurar que ninguna de ellas impida a las personas con discapacidad disfrutar de la igualdad de oportunidades. Las organizaciones empresariales pueden contribuir a estos esfuerzos recopilando los numerosos ejemplos de buenas prácticas ya existentes.</li>
                        </ul>
                </div>
            </div>
        </section>
        <section class="main_contacto">
            <div class="maps">
                <h2>Ubicacion</h2>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3561.6859010894054!2d-60.4488329495542!3d-26.786280494311505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94412ce3c68bc62f%3A0x8c842a33abd51d5a!2sDorrego%20490%2C%20H3700IAJ%20S%C3%A1enz%20Pe%C3%B1a%2C%20Chaco!5e0!3m2!1ses!2sar!4v1670109639333!5m2!1ses!2sar" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </section>
    </main>
    {% endblock  %}

</body>

</html>

blog/templates/noticia/asce.html
{% extends 'noticiaBase.html' %} 
{% load static %} 
{% block title %} Noticias{% endblock %} 

{% block noticia %}

<article class="articulo">
  {% for noti in antiguo %}
  <div class="contenedorNoticia">
    <img src="{{noti.imagen.url}}" alt="Imágen Noticia" class="img-noticia">
    <div class="contenedorTexto">
      <div class="texto-articulo">
        <h3 class="tituloNoticia">{{noti.titulo}}</h3>
        <p class="resumenNoticia">{{noti.resumen}}</p>
      </div>
      <div class="btn-articulo">
        <a href="{% url 'noticias:detalle' noti.id %}" class="leerMas">Leer más</a>
      </div>
    </div>
  </div>
  {% endfor %}
</article>

{% endblock %}

blog/templates/noticia/categoria.html
{% extends 'noticiaBase.html' %} 
{% load static %} 
{% block title %} Noticias{% endblock %} 

{% block noticia %}


{% if ban %}
<article class="articulo">
  {% for noti in filtro %}
  <div class="contenedorNoticia">
    <img src="{{noti.imagen.url}}" alt="Imágen Noticia" class="img-noticia">
    <div class="contenedorTexto">
      <div class="texto-articulo">
        <h3 class="tituloNoticia">{{noti.titulo}}</h3>
        <p class="resumenNoticia">{{noti.resumen}}</p>
      </div>
      <div class="btn-articulo">
        <a href="{% url 'noticias:detalle' noti.id %}" class="leerMas">Leer más</a>
      </div>
    </div>
  </div>
  {% endfor %}
</article>
{% else %}
<div class="sin-noticias">
  <h2>Todavia no hay noticias de esta Categori.....</h2>
</div>

{% endif %}

{% endblock %}

blog/templates/noticia/desc.html
{% extends 'noticiaBase.html' %} 
{% load static %} 
{% block title %} Noticias{% endblock %} 

{% block noticia %}



<article class="articulo">
  {% for noti in nuevas %}
  <div class="contenedorNoticia">
    <img src="{{noti.imagen.url}}" alt="Imágen Noticia" class="img-noticia">
    <div class="contenedorTexto">
      <div class="texto-articulo">
        <h3 class="tituloNoticia">{{noti.titulo}}</h3>
        <p class="resumenNoticia">{{noti.resumen}}</p>
      </div>
      <div class="btn-articulo">
        <a href="{% url 'noticias:detalle' noti.id %}" class="leerMas">Leer más</a>
      </div>
    </div>
  </div>
  {% endfor %}
</article>


{% endblock %}

blog/templates/noticia/detalle.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} Noticia {{noticia.titulo}}{% endblock %} 
{% block contenedor %}
<main class="detalle">
    <div class="contenedor_detalle">
        <section class="content-detalle-noticia">
            <div class="titulo-detalle-noticia">
                <h2>{{noticia.titulo}}</h2>
            </div>
            <div class="img-detalle-noticia">
                <img src="{{noticia.imagen.url}}">
            </div>
            <div class="fecha-categoria-detalle-noticia">
                <p>FECHA: {{noticia.fecha}}</p>
                <p>CATEGORÍA: {{noticia.categoría_noticia}}</p>
            </div>
            <hr class="divisoria">
            <div class="cuerpo-detalle-noticia">
                <h3>Noticia:</h3>
                <p>{{noticia.cuerpo}}</p>
            </div>
        </section>
        <hr class="divisoria">

        <section class="add-comentarios">

            <form class="add-comentarios-form" action="{% url 'noticias:comentar' %}" method="POST">

                {% csrf_token %}
                <textarea class="input" name="comentario" max-length="1500" placeholder="Escribe tu comentario..."></textarea>
                <input type="text" name="id_noticia" value="{{noticia.id}}" hidden="">
                <div class="btn-detalle">
                    <button type="submit" class="button">Comentar</button>
                </div>

            </form>

        </section>
        
        <hr class="divisoria">
        <section class="get-comentarios">
            <h3 class="titulo_comentarios">Comentarios:</h3>
            {% for c in comentario %}
            <div class="card-content-comentario">
                <div class="card-usuario">
                    <h4>{{c.usuario}}</h4>
                </div>
                <div class="card-fecha">
                    <p>{{c.fecha}}</p>
                </div>
                <div class="card-comentario">
                    <p>{{c.comentario}}</p>
                </div>
            </div>
            {% endfor %}
        </section>   
    </div> 
</main>

{% endblock %}

blog/templates/noticia/noticias.html
{% extends 'noticiaBase.html' %} 
{% load static %} 
{% block title %} Noticias{% endblock %} 

{% block noticia %}
<article class="articulo">
    {% for i in noticia %}
    <div class="contenedorNoticia">
      <img src="{{i.imagen.url}}" alt="Imágen Noticia" class="img-noticia">
      <div class="contenedorTexto">
        <div class="texto-articulo">
          <h3 class="tituloNoticia">{{i.titulo}}</h3>
          <p class="resumenNoticia">{{i.resumen}}</p>
        </div>
        <div class="btn-articulo">
          <a href="{% url 'noticias:detalle' i.id %}" class="leerMas">Leer más</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </article>
{% endblock %}

blog/templates/noticiaBase.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} {% endblock %} 
{% block contenedor %}
<main class="main-noticias">
  <section class="section-noticias-ultimas_noticias">
    <div class="titulo-buscador-ultimas_noticias">
      <h2>Últimas Noticias</h2>

        <div class="buscador">
            Filtrar
            <div class="dropdown">
              <img class ="img-drop" src="{% static 'img/filtro60.png'%}" alt="">
                <div class="dropdown-content">
                  <a href="{% url 'noticias:ultima' %}">Mostrar todas</a>
                {% for c in categoria%}
                  <a href="{%  url 'noticias:filtro' c.id  %}">{{ c.nombre }}</a>
                {% endfor %}
                <a href="{%  url 'noticias:asce' %}">Ascendente</a>
                <a href="{%  url 'noticias:desc' %}">Descendiente</a>
                </div>
            </div>
        </div>
    </div>

    <div class="contenedor-ultimas_noticias">
      <p class="mensaje_construccion">Noticias en Construccíon</p>
      {% for noti in noticiaUlt %}
      <div class="noticia" style="background-image: url({{noti.imagen.url}})">
        <img src="{{noti.imagen.url}}" alt="" />
        <div class="descripcion">
          <h3>{{noti.titulo}}</h3>
          <p>
            {{noti.resumen}}
          </p>
        </div>
      </div>
      {% endfor %}

      <button class="cambio-noticias btn-left"><</button>
      <button class="cambio-noticias btn-rigth">></button>
    </div>
  </section>
</main>
{% block noticia %}
{% endblock %}
{% endblock %}

blog/templates/noticias.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} Noticias{% endblock %} 
{% block contenedor %}

<main class="main-noticias">
  <section class="section-noticias-ultimas_noticias">
    <div class="titulo-buscador-ultimas_noticias">
      <h2>Ultimas Noticias</h2>

      <div class="buscador">
        <input type="text" placeholder="Busqueda por categoria y noticia" />
        <button><img src="{% static 'img/busquedad.png' %}" alt="" /></button>
      </div>
    </div>

    <div class="contenedor-ultimas_noticias">
      {% for i in noticiaUlt %}
      <div
        class="noticia noticia-card1"
        style="background-image: url({% static 'img/pruebas/73294.jpg'%})"
      >
        <img src="{% static 'img/pruebas/73294.jpg' %}" alt="" />
        <div class="descripcion">
          <h3>{{i.titulo}}</h3>
          <p>
            {{i.cuerpo}}
          </p>
        </div>
      </div>

      {% endfor %}
      <button class="cambio-noticias btn-left"><</button>
      <button class="cambio-noticias btn-rigth">></button>
    </div>
  </section>
</main>
<article class="articulo">
  {% for i in noticia %}
  <div class="contenedorNoticia">
    <img src="{% static 'img/pruebas/messi.jpg' %}" alt="Imágen Noticia" class="img-noticia">
    <div class="contenedorTexto">
      <div class="texto-articulo">
        <h3 class="tituloNoticia">{{i.titulo}}</h3>
        <p class="resumenNoticia">{{i.cuerpo}}</p>
      </div>
      <div class="btn-articulo">
        <a href="#" class="leerMas">Leer más</a>
      </div>
    </div>
  </div>
  {% endfor %}
</article>
{% endblock %}

blog/templates/usuarios/login.html
{% extends 'base.html' %} {% load static %} {% block title %} Login{% endblock%}
{% block contenedor %}
<main class="main-login" role="main">
  <h3 class="mb-4">Ingreso de usuario</h3>
  <div class="container">
    <div class="img-forms div-img-left">
      <img src="{% static 'img/logoPrincipal.png'%}" alt="logo" />
    </div>
    <form class="form-registrar form-login" method="POST">
      {%csrf_token%} 
      {% if  form.errors %}
        <p>Usuario no registrado</p>
      {% endif %}
      <div class="contenedor_input">
        <label for="nombre">Nombre </label>
        <input type="text" name="username" id="nombre" placeholder="USUARIO" />
      </div>
      <div class="contenedor_input">
        <label for="password1">Contraseña </label>
        <input
          type="password"
          name="password"
          id="password1"
          placeholder="PASSWORD"
        />
      </div>
      <input type="submit" class="btn-registrar" name="" value="ENVIAR" />
    </form>
    <div class="img-forms">
      <img src="{% static 'img/logoEscuela.png'%}" alt="logo" />
    </div>
  </div>
</main>
{% endblock %}